- name: Checkout my dotfiles
  git:
    repo: https://github.com/naofumi-fujii/dotfiles.git
    dest: ~/dotfiles

- name: Create symlinks
  file:
    src: ~/dotfiles/{{ item }}
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - .tmux.conf
    - .zshrc
    - .gitconfig
    - .gitignore
    - .vimrc
    - .bundle
    - .gemrc
